use super::utils::{base_options, BaseOption};
use crate::{
    db::get_username,
    error::{ApiError, ApiResult, RedirectTo, Result, WithStatus},
    index_manager::IndexManager,
    jobs::OptionsDef,
    session::Session,
    Context, LobbyConfig, TplContext,
};
use anyhow::anyhow;
use askama::Template;
use askama_web::WebTemplate;
use deadpool_redis::Pool as RedisPool;
use flate2::{read::GzDecoder, write::GzEncoder, Compression};
use http::header::CONTENT_DISPOSITION;
use indexmap::IndexMap;
use redis::AsyncCommands;
use rocket::{
    form::Form,
    http::{uri::Host, Header, Status},
    FromForm, Route, State,
};
use semver::Version;
use std::{
    collections::{HashMap, HashSet},
    str::FromStr,
    time::Duration,
};
use tracing_opentelemetry::OpenTelemetrySpanExt;
use wq::JobStatus;

use crate::jobs::{OptionsGenParams, OptionsGenQueue};

const WEIGHTED_TYPES: &[&str] = &[
    "bool",
    "choice",
    "named_range",
    "text_choice",
    "range",
    "text",
];

async fn get_default_player_name(session: &Session, ctx: &Context) -> String {
    let Some(user_id) = session.user_id else {
        return "Player{NUMBER}".to_string();
    };
    let mut conn = ctx.db_pool.get().await.unwrap();
    let Ok(Some(username)) = get_username(user_id, &mut conn).await else {
        return "Player{NUMBER}".to_string();
    };
    let truncated = username.chars().take(14).collect::<String>();
    format!("{}{{NUMBER}}", truncated)
}

/// Option definitions never change for a given apworld version, the expiry is there to shed the
/// ones nobody asks for anymore and to pick up fixes to the generator within a day.
const OPTIONS_CACHE_TTL_SECS: u64 = 24 * 3600;

/// The option definitions generated by the workers, kept in Valkey.
///
/// They can't live in the memory of a lobby process: a worker reports a finished job to
/// whichever lobby process its connection is on, and the request waiting for that job may be
/// served by another one.
///
/// A definition belongs to the Archipelago version, the base, whose worker generated it: the
/// same release of a world can have other options, or none, on another base.
#[derive(Clone)]
pub struct OptionsCache {
    redis_pool: RedisPool,
    legacy_base: Version,
}

impl OptionsCache {
    /// `legacy_base` is the base whose definitions keep the keys they had before definitions
    /// had a base: every definition from then was generated on it.
    pub fn new(redis_pool: RedisPool, legacy_base: Version) -> Self {
        Self {
            redis_pool,
            legacy_base,
        }
    }

    pub fn legacy_base(&self) -> &Version {
        &self.legacy_base
    }

    fn key(&self, base: &Version, apworld_name: &str, version: &Version) -> String {
        if base == &self.legacy_base {
            format!("options_def:{apworld_name}:{version}")
        } else {
            format!("options_def:base:{base}:{apworld_name}:{version}")
        }
    }

    pub async fn get(
        &self,
        base: &Version,
        apworld_name: &str,
        version: &Version,
    ) -> anyhow::Result<Option<OptionsDef>> {
        let mut redis = self.redis_pool.get().await?;
        let stored: Option<Vec<u8>> = redis.get(self.key(base, apworld_name, version)).await?;
        let Some(stored) = stored else {
            return Ok(None);
        };

        match decode_options_def(&stored) {
            Ok(options) => Ok(Some(options)),
            Err(e) => {
                // Written by a lobby with another idea of what definitions look like
                tracing::warn!(%base, %apworld_name, %version, %e, "Ignoring unreadable option definitions");
                Ok(None)
            }
        }
    }

    pub async fn contains(
        &self,
        base: &Version,
        apworld_name: &str,
        version: &Version,
    ) -> anyhow::Result<bool> {
        let mut redis = self.redis_pool.get().await?;

        Ok(redis.exists(self.key(base, apworld_name, version)).await?)
    }

    pub async fn insert(
        &self,
        base: &Version,
        apworld_name: &str,
        version: &Version,
        options: &OptionsDef,
    ) -> anyhow::Result<()> {
        let mut redis = self.redis_pool.get().await?;
        redis
            .set_ex::<_, _, ()>(
                self.key(base, apworld_name, version),
                encode_options_def(options)?,
                OPTIONS_CACHE_TTL_SECS,
            )
            .await?;

        Ok(())
    }
}

// Definitions are mostly lists of item and location names repeated across options. They
// average 140kB as JSON and compress to an eighth of that.
fn encode_options_def(options: &OptionsDef) -> anyhow::Result<Vec<u8>> {
    let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
    serde_json::to_writer(&mut encoder, options)?;

    Ok(encoder.finish()?)
}

fn decode_options_def(stored: &[u8]) -> anyhow::Result<OptionsDef> {
    Ok(serde_json::from_reader(GzDecoder::new(stored))?)
}

#[derive(rocket::Responder)]
#[response(status = 200, content_type = "application/yaml")]
pub struct YamlDownload<'a> {
    pub content: String,
    pub headers: Header<'a>,
}

#[derive(Template, WebTemplate)]
#[template(path = "options.html")]
struct OptionsTpl<'a> {
    base: TplContext<'a>,
    // apworld_name, world_name
    apworlds: Vec<(String, String)>,
    versions: Vec<String>,
    selected_apworld: Option<String>,
    selected_version: Option<String>,
    options: Option<OptionsDef>,

    warnings: Vec<String>,
    prefilled_values: Option<HashMap<String, serde_json::Value>>,
    prefilled_player_name: Option<String>,
    prefilled_description: Option<String>,
    yaml_option_names: HashSet<String>,
    // Options whose prefilled values are no longer valid for the current definitions
    outdated_values: HashSet<String>,
    default_player_name: String,
    // Ends every options URL of the page, to stay on the Archipelago version it is about
    base_query: String,
    // The Archipelago versions to choose from, when there is more than one
    base_options: Vec<BaseOption>,
}

impl OptionsTpl<'_> {
    fn get_prefilled(&self, option_name: &str) -> Option<&serde_json::Value> {
        self.prefilled_values
            .as_ref()
            .and_then(|pv| pv.get(option_name))
    }

    // Helper functions for template value extraction
    fn prefilled_bool(&self, prefilled: &Option<&serde_json::Value>, default: bool) -> bool {
        prefilled
            .and_then(|v| {
                v.as_bool().or_else(|| match v.as_str() {
                    Some("true") => Some(true),
                    Some("false") => Some(false),
                    _ => None,
                })
            })
            .unwrap_or(default)
    }

    fn prefilled_num(&self, prefilled: &Option<&serde_json::Value>) -> Option<i64> {
        prefilled.and_then(|v| {
            v.as_i64()
                .or_else(|| v.as_str().and_then(|s| s.parse().ok()))
        })
    }

    fn prefilled_str<'a>(&self, prefilled: &'a Option<&'a serde_json::Value>) -> Option<&'a str> {
        prefilled.and_then(|v| v.as_str())
    }

    fn prefilled_array<'a>(
        &self,
        prefilled: &'a Option<&'a serde_json::Value>,
    ) -> Option<&'a Vec<serde_json::Value>> {
        prefilled.and_then(|v| v.as_array())
    }

    fn prefilled_object<'a>(
        &self,
        prefilled: &'a Option<&'a serde_json::Value>,
    ) -> Option<&'a serde_json::Map<String, serde_json::Value>> {
        prefilled.and_then(|v| v.as_object())
    }

    fn array_contains_str(&self, arr: &[serde_json::Value], s: &str) -> bool {
        arr.iter().any(|v| v.as_str() == Some(s))
    }

    fn suggestions_contain(&self, suggestions: &[String], s: &str) -> bool {
        suggestions.iter().any(|sug| sug == s)
    }

    fn prefilled_is_suggestion(
        &self,
        prefilled: &Option<&serde_json::Value>,
        option_def: &crate::jobs::OptionDef,
    ) -> bool {
        let Some(pstr) = self.prefilled_str(prefilled) else {
            return false;
        };
        let Some(suggestions) = &option_def.suggestions else {
            return false;
        };
        suggestions.iter().any(|s| s == pstr)
    }

    fn default_is_suggestion(&self, option_def: &crate::jobs::OptionDef) -> bool {
        let Some(default_str) = option_def.default.as_str() else {
            return false;
        };
        let Some(suggestions) = &option_def.suggestions else {
            return false;
        };
        suggestions.iter().any(|s| s == default_str)
    }

    fn default_str<'a>(&self, option_def: &'a crate::jobs::OptionDef) -> Option<&'a str> {
        option_def.default.as_str()
    }

    fn is_weighted(
        &self,
        option_def: &crate::jobs::OptionDef,
        prefilled: &Option<&serde_json::Value>,
    ) -> bool {
        WEIGHTED_TYPES.contains(&option_def.ty.as_str())
            && prefilled.map(|v| v.is_object()).unwrap_or(false)
    }

    fn weights_json(&self, prefilled: &Option<&serde_json::Value>) -> String {
        prefilled
            .and_then(|v| v.as_object())
            .map(|obj| serde_json::to_string(obj).unwrap_or_default())
            .unwrap_or_default()
    }

    fn prefilled_json(&self, prefilled: &Option<&serde_json::Value>) -> String {
        prefilled
            .map(|v| serde_json::to_string(v).unwrap_or_default())
            .unwrap_or_default()
    }

    fn is_new_option(&self, option_name: &str) -> bool {
        self.prefilled_values.is_some() && !self.yaml_option_names.contains(option_name)
    }

    fn is_outdated(&self, option_name: &str) -> bool {
        self.outdated_values.contains(option_name)
    }
}

/// The Archipelago version an options page or API call is about: the one its `base`
/// parameter names, which has to be on offer here, or the default one without it.
pub(crate) async fn requested_base(
    index_manager: &IndexManager,
    base: Option<&str>,
) -> anyhow::Result<Version> {
    let Some(base) = base else {
        return Ok(index_manager.default_base().await);
    };
    let base =
        Version::from_str(base).map_err(|_| anyhow!("{base:?} isn't an Archipelago version"))?;
    if !index_manager.offers(&base).await {
        return Err(anyhow!("This lobby doesn't offer Archipelago {base}"));
    }

    Ok(base)
}

/// The entries of a selector of the version a page is about, with `base` selected. None when
/// there is nothing to choose.
pub(crate) async fn selectable_bases(
    index_manager: &IndexManager,
    base: &Version,
) -> Vec<BaseOption> {
    let offered = index_manager.offered_bases().await;
    if offered.len() < 2 {
        return vec![];
    }

    base_options(&offered, Some(base))
}

/// What an options URL needs at its end to be about `base`: nothing for the default base,
/// `?base=<version>` for another one.
pub(crate) async fn base_query(index_manager: &IndexManager, base: &Version) -> String {
    if base == &index_manager.default_base().await {
        return String::new();
    }

    // A `+` in a query is a space
    format!("?base={}", base.to_string().replace('+', "%2B"))
}

/// Helper to fetch OptionsDef, using cache if available or queuing a job if not.
///
/// `base` is the Archipelago version the definitions are for. A worker running it generates
/// them, and they are cached for it alone.
#[tracing::instrument(skip(options_gen_queue, options_cache))]
pub(crate) async fn get_options_def(
    apworld_name: &str,
    version: &Version,
    base: &Version,
    options_gen_queue: &State<OptionsGenQueue>,
    options_cache: &State<OptionsCache>,
) -> Result<OptionsDef> {
    if let Some(cached_options) = options_cache.get(base, apworld_name, version).await? {
        return Ok(cached_options);
    }

    let mut params = OptionsGenParams {
        apworld: (apworld_name.to_string(), version.clone()),
        otlp_context: HashMap::new(),
        ap_version: Some(base.clone()),
    };

    let cx = tracing::Span::current().context();
    opentelemetry::global::get_text_map_propagator(|propagator| {
        propagator.inject_context(&cx, &mut params.otlp_context)
    });

    let job_id = options_gen_queue
        .enqueue_job_in(
            Some(&base.to_string()),
            &params,
            wq::Priority::High,
            Duration::from_secs(30),
        )
        .await?;

    let Some(status) = options_gen_queue
        .wait_for_job(&job_id, Some(Duration::from_secs(30)))
        .await?
    else {
        tracing::error!(%job_id, %apworld_name, %version, "Options gen job timed out");
        Err(anyhow!(
            "The option definitions could not get fetched, try again in a bit"
        ))?
    };
    if matches!(status, JobStatus::InternalError) {
        tracing::error!(%job_id, %apworld_name, %version, "Options gen job returned internal error");
        Err(anyhow!(
            "There was an unexpected error while generating option definitions, try again."
        ))?
    }
    if matches!(status, JobStatus::Failure) {
        tracing::error!(%job_id, %apworld_name, %version, "Options gen job failed");
        Err(anyhow!("Generating option definitions failed, try again."))?
    }

    // The queue callback stored them before the job got reported as resolved. That callback may
    // have run in another lobby process than this one.
    options_cache
        .get(base, apworld_name, version)
        .await?
        .ok_or_else(|| anyhow!("Options not found in cache after successful job").into())
}

pub struct OptionsPreloadFairing;

#[rocket::async_trait]
impl rocket::fairing::Fairing for OptionsPreloadFairing {
    fn info(&self) -> rocket::fairing::Info {
        rocket::fairing::Info {
            name: "Options Preload",
            kind: rocket::fairing::Kind::Liftoff,
        }
    }

    #[tracing::instrument(name = "options_preload", skip_all)]
    async fn on_liftoff(&self, rocket: &rocket::Rocket<rocket::Orbit>) {
        if std::env::var("PRELOAD_OPTIONS_DEFS").is_err() {
            return;
        }

        let index_manager = rocket.state::<IndexManager>().unwrap();
        let options_gen_queue = rocket.state::<OptionsGenQueue>().unwrap();
        let options_cache = rocket.state::<OptionsCache>().unwrap();

        // The latest release of every world, for every base on offer
        let mut worlds = Vec::new();
        for base in index_manager.offered_bases().await {
            let Ok(index) = index_manager.index_for(&base).await else {
                continue;
            };
            worlds.extend(index.worlds.iter().filter_map(|(apworld_name, world)| {
                let latest_version = world.versions.keys().max()?;
                Some((base.clone(), apworld_name.clone(), latest_version.clone()))
            }));
        }

        tracing::info!("Enqueuing options preload for {} worlds", worlds.len());

        for (base, apworld_name, version) in worlds {
            // Every lobby process preloads on startup, and they all share the cache
            if matches!(
                options_cache.contains(&base, &apworld_name, &version).await,
                Ok(true)
            ) {
                continue;
            }

            let mut params = OptionsGenParams {
                apworld: (apworld_name.clone(), version.clone()),
                otlp_context: HashMap::new(),
                ap_version: Some(base.clone()),
            };

            let cx = tracing::Span::current().context();
            opentelemetry::global::get_text_map_propagator(|propagator| {
                propagator.inject_context(&cx, &mut params.otlp_context)
            });

            if let Err(e) = options_gen_queue
                .enqueue_job_in(
                    Some(&base.to_string()),
                    &params,
                    wq::Priority::Low,
                    Duration::from_secs(120),
                )
                .await
            {
                tracing::warn!(%apworld_name, %version, %e, "Failed to enqueue preload job");
            }
        }
    }
}

// The options pages are about one Archipelago version, the default one unless `?base=` names
// another. Every link and form on them carries it along, see `base_query`.

#[rocket::get("/options/<apworld_name>/<version>?<base>")]
#[tracing::instrument(skip(
    options_gen_queue,
    options_cache,
    index_manager,
    ctx,
    session,
    redirect_to
))]
async fn options_gen_api<'a>(
    apworld_name: &'a str,
    version: String,
    base: Option<&'a str>,
    options_gen_queue: &State<OptionsGenQueue>,
    options_cache: &State<OptionsCache>,
    index_manager: &'a State<IndexManager>,
    ctx: &'a State<Context>,
    lobby_config: &State<LobbyConfig>,
    session: Session,
    redirect_to: &RedirectTo,
) -> Result<OptionsTpl<'a>> {
    redirect_to.set("/options");
    let base = requested_base(index_manager, base).await?;
    let index = index_manager.index_for(&base).await?;
    let Some(apworld) = index.worlds.get(apworld_name) else {
        Err(anyhow!("Unknown apworld"))?
    };
    let mut apworlds: Vec<(String, String)> = index
        .worlds
        .iter()
        .map(|(apworld_name, world)| (apworld_name.clone(), world.display_name.clone()))
        .collect();
    apworlds.sort_by_key(|(_, world_name)| world_name.to_lowercase());
    let versions: Vec<String> = apworld
        .versions
        .keys()
        .map(|v| v.to_string())
        .rev()
        .collect();
    if !versions.contains(&version.to_string()) {
        Err(anyhow!("Unknown version for this apworld"))?
    }
    let display_name = apworld.display_name.clone();
    drop(index);

    let parsed_version = Version::from_str(&version)?;
    let options = get_options_def(
        apworld_name,
        &parsed_version,
        &base,
        options_gen_queue,
        options_cache,
    )
    .await?;

    let default_player_name = get_default_player_name(&session, ctx).await;
    let base_options = selectable_bases(index_manager, &base).await;
    let base_query = base_query(index_manager, &base).await;

    Ok(OptionsTpl {
        base: TplContext::from_session(
            "options",
            session,
            ctx,
            lobby_config,
            Some(format!("Options Generator - {}", display_name)),
        )
        .await,
        apworlds,
        versions,
        selected_apworld: Some(apworld_name.to_string()),
        selected_version: Some(version.to_string()),
        options: Some(options),
        warnings: vec![],
        prefilled_values: None,
        prefilled_player_name: None,
        prefilled_description: None,
        yaml_option_names: HashSet::new(),
        outdated_values: HashSet::new(),
        default_player_name,
        base_query,
        base_options,
    })
}

#[rocket::get("/options/<apworld_name>?<base>")]
#[tracing::instrument(skip(
    options_gen_queue,
    options_cache,
    index_manager,
    ctx,
    session,
    redirect_to
))]
async fn options_apworld_versions<'a>(
    apworld_name: &'a str,
    base: Option<&'a str>,
    index_manager: &'a State<IndexManager>,
    options_gen_queue: &State<OptionsGenQueue>,
    options_cache: &State<OptionsCache>,
    ctx: &'a State<Context>,
    lobby_config: &State<LobbyConfig>,
    session: Session,
    redirect_to: &RedirectTo,
) -> Result<OptionsTpl<'a>> {
    redirect_to.set("/options");
    let last_version = {
        let wanted_base = requested_base(index_manager, base).await?;
        let index = index_manager.index_for(&wanted_base).await?;
        let Some(apworld) = index.worlds.get(apworld_name) else {
            Err(anyhow!("Unknown apworld"))?
        };
        apworld
            .versions
            .keys()
            .max()
            .ok_or_else(|| anyhow!("This apworld has no version"))?
            .to_string()
    };

    options_gen_api(
        apworld_name,
        last_version,
        base,
        options_gen_queue,
        options_cache,
        index_manager,
        ctx,
        lobby_config,
        session,
        redirect_to,
    )
    .await
}

#[rocket::get("/options?<base>")]
#[tracing::instrument(skip(index_manager, ctx, session, redirect_to))]
async fn options_gen<'a>(
    base: Option<&str>,
    index_manager: &State<IndexManager>,
    ctx: &'a State<Context>,
    session: Session,
    lobby_config: &State<LobbyConfig>,
    redirect_to: &RedirectTo,
) -> Result<OptionsTpl<'a>> {
    // Only `base` can be wrong here, and the page without it always works
    redirect_to.set("/options");
    let base = requested_base(index_manager, base).await?;
    let index = index_manager.index_for(&base).await?;
    let mut apworlds: Vec<(String, String)> = index
        .worlds
        .iter()
        .map(|(apworld_name, world)| (apworld_name.clone(), world.display_name.clone()))
        .collect();
    apworlds.sort_by_key(|(_, world_name)| world_name.to_lowercase());

    let default_player_name = get_default_player_name(&session, ctx).await;
    let base_options = selectable_bases(index_manager, &base).await;
    let base_query = base_query(index_manager, &base).await;

    Ok(OptionsTpl {
        base: TplContext::from_session(
            "options",
            session,
            ctx,
            lobby_config,
            Some("Options Generator".to_string()),
        )
        .await,
        apworlds,
        versions: vec![],
        selected_apworld: None,
        selected_version: None,
        options: None,
        warnings: vec![],
        prefilled_values: None,
        prefilled_player_name: None,
        prefilled_description: None,
        yaml_option_names: HashSet::new(),
        outdated_values: HashSet::new(),
        default_player_name,
        base_query,
        base_options,
    })
}

#[derive(FromForm)]
struct YamlUpload<'a> {
    yaml: &'a str,
}

fn validate_option_value(value: &serde_json::Value, option_def: &crate::jobs::OptionDef) -> bool {
    // For weighted options, only validate non-zero weighted values
    if let Some(obj) = value.as_object() {
        return obj
            .iter()
            .filter(|(_, v)| v.as_i64().map(|n| n != 0).unwrap_or(true))
            .all(|(k, _)| validate_single_value(k, option_def));
    }

    if let Some(s) = value.as_str() {
        return validate_single_value(s, option_def);
    }
    if let Some(n) = value.as_i64() {
        return validate_numeric_value(n, option_def);
    }
    if let Some(arr) = value.as_array() {
        if !option_def.has_valid_keys() {
            return true;
        }
        let valid_keys = option_def.valid_keys();
        return arr.iter().all(|v| {
            v.as_str()
                .map(|s| valid_keys.iter().any(|k| k == s))
                .unwrap_or(true)
        });
    }
    true
}

fn validate_single_value(value: &str, option_def: &crate::jobs::OptionDef) -> bool {
    // "random", "random-low", "random-high", etc. are always valid
    if value.starts_with("random") {
        return true;
    }

    match option_def.ty.as_str() {
        "choice" => option_def
            .choices
            .as_ref()
            .map(|c| c.iter().any(|choice| choice == value))
            .unwrap_or(true),
        "text_choice" => option_def
            .suggestions
            .as_ref()
            .map(|s| s.iter().any(|sug| sug == value))
            .unwrap_or(true),
        "named_range" => {
            if let Some(suggestions) = &option_def.suggestions {
                if suggestions.iter().any(|s| s == value) {
                    return true;
                }
            }
            if let Ok(n) = value.parse::<i64>() {
                return validate_numeric_value(n, option_def);
            }
            false
        }
        _ => true,
    }
}

fn validate_numeric_value(value: i64, option_def: &crate::jobs::OptionDef) -> bool {
    match option_def.ty.as_str() {
        "range" | "named_range" => {
            if let Some((min, max)) = option_def.range {
                value >= min && value <= max
            } else {
                true
            }
        }
        _ => true,
    }
}

#[rocket::post("/options/edit?<base>", data = "<form>")]
#[tracing::instrument(skip(options_gen_queue, options_cache, index_manager, ctx, session, form))]
async fn edit_yaml<'a>(
    base: Option<&str>,
    form: Form<YamlUpload<'a>>,
    options_gen_queue: &State<OptionsGenQueue>,
    options_cache: &State<OptionsCache>,
    index_manager: &'a State<IndexManager>,
    ctx: &'a State<Context>,
    redirect_to: &RedirectTo,
    session: Session,
    lobby_config: &State<LobbyConfig>,
) -> Result<OptionsTpl<'a>> {
    redirect_to.set("/options");

    let yaml: serde_json::Value =
        serde_saphyr::from_str(form.yaml).map_err(|e| anyhow!("Failed to parse YAML: {}", e))?;

    let player_name = yaml
        .get("name")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string());

    let description = yaml
        .get("description")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string());

    let game_field = yaml
        .get("game")
        .ok_or_else(|| anyhow!("YAML is missing 'game' field"))?;

    let game_name = if let Some(s) = game_field.as_str() {
        s.to_string()
    } else if game_field.is_object() {
        return Err(anyhow!(
            "Weighted game randomizers are not supported. Please use a YAML with a single game."
        )
        .into());
    } else {
        return Err(anyhow!("Invalid 'game' field in YAML").into());
    };

    let base = requested_base(index_manager, base).await?;
    let index = index_manager.index_for(&base).await?;
    let (apworld_name, latest_version, display_name) = index
        .worlds
        .iter()
        .find(|(_, world)| world.name == game_name)
        .map(|(name, world)| {
            let latest = world.versions.keys().max().unwrap().clone();
            (name.clone(), latest, world.display_name.clone())
        })
        .ok_or_else(|| anyhow!("Game '{}' not found", game_name))?;

    let mut apworlds: Vec<(String, String)> = index
        .worlds
        .iter()
        .map(|(apworld_name, world)| (apworld_name.clone(), world.display_name.clone()))
        .collect();
    apworlds.sort_by_key(|(_, world_name)| world_name.to_lowercase());

    let versions: Vec<String> = index
        .worlds
        .get(&apworld_name)
        .unwrap()
        .versions
        .keys()
        .map(|v| v.to_string())
        .rev()
        .collect();
    drop(index);

    let options = get_options_def(
        &apworld_name,
        &latest_version,
        &base,
        options_gen_queue,
        options_cache,
    )
    .await?;

    let option_defs: HashMap<&String, &crate::jobs::OptionDef> = options
        .iter()
        .flat_map(|(_, group_options)| group_options.iter())
        .collect();

    let game_options = yaml.get(&game_name).and_then(|v| v.as_object());

    let mut prefilled_values: HashMap<String, serde_json::Value> = HashMap::new();
    let mut warnings: Vec<String> = vec![];
    let mut yaml_option_names: HashSet<String> = HashSet::new();
    let mut outdated_values: HashSet<String> = HashSet::new();

    if let Some(game_opts) = game_options {
        for (key_str, value) in game_opts {
            yaml_option_names.insert(key_str.clone());

            let Some(option_def) = option_defs.get(key_str) else {
                warnings.push(key_str.clone());
                continue;
            };

            let is_weighted_type = WEIGHTED_TYPES.contains(&option_def.ty.as_str());
            if value.is_object()
                && option_def.ty != "counter"
                && option_def.ty != "dict"
                && !is_weighted_type
            {
                warnings.push(format!(
                    "{} (weighted options not supported for this type)",
                    key_str
                ));
                continue;
            }

            let coalesced = value.as_object().and_then(|mapping| {
                if !is_weighted_type {
                    return None;
                }
                let non_zero: Vec<_> = mapping
                    .iter()
                    .filter(|(_, v)| v.as_i64().map(|n| n != 0).unwrap_or(true))
                    .collect();
                if non_zero.len() == 1 {
                    Some(serde_json::Value::String(non_zero[0].0.clone()))
                } else {
                    None
                }
            });

            let json_value = coalesced.unwrap_or_else(|| value.clone());

            if option_def.is_editable() && !validate_option_value(&json_value, option_def) {
                outdated_values.insert(key_str.clone());
                // If invalid, don't insert it in prefill so it gets reset
                continue;
            }

            prefilled_values.insert(key_str.clone(), json_value);
        }
    }

    // If we have a prefilled player name, then the default doesn't matter since it won't be used
    let default_player_name = match &player_name {
        Some(_) => "Player{NUMBER}".to_string(),
        None => get_default_player_name(&session, ctx).await,
    };
    let base_options = selectable_bases(index_manager, &base).await;
    let base_query = base_query(index_manager, &base).await;

    Ok(OptionsTpl {
        base: TplContext::from_session(
            "options",
            session,
            ctx,
            lobby_config,
            Some(format!("Options Generator - {}", display_name)),
        )
        .await,
        apworlds,
        versions,
        selected_apworld: Some(apworld_name),
        selected_version: Some(latest_version.to_string()),
        options: Some(options),
        warnings,
        prefilled_values: Some(prefilled_values),
        prefilled_player_name: player_name,
        prefilled_description: description,
        yaml_option_names,
        outdated_values,
        default_player_name,
        base_query,
        base_options,
    })
}

#[rocket::post("/options/<apworld_name>/<version>/download?<base>", data = "<form>")]
#[tracing::instrument(skip(host, index_manager, form, options_gen_queue, options_cache))]
async fn download_yaml<'a>(
    apworld_name: &str,
    version: &str,
    base: Option<&str>,
    host: &Host<'_>,
    form: Form<HashMap<String, String>>,
    index_manager: &State<IndexManager>,
    options_gen_queue: &State<OptionsGenQueue>,
    options_cache: &State<OptionsCache>,
) -> ApiResult<YamlDownload<'a>> {
    // The page fetches this and saves whatever comes back, so a failure has to be an error
    // status with its message as the body. A redirect would get followed and saved as the YAML.
    let not_found = |message: &'static str| ApiError {
        error: anyhow!(message),
        status: Status::NotFound,
    };

    let parsed_version = Version::from_str(version).map_err(|_| not_found("Invalid version"))?;
    let base = requested_base(index_manager, base)
        .await
        .map_err(|_| not_found("Unknown Archipelago version"))?;
    let game_name = {
        let index = index_manager.index_for(&base).await?;
        let Some(apworld) = index.worlds.get(apworld_name) else {
            return Err(not_found("Unknown apworld"));
        };
        if !apworld.versions.contains_key(&parsed_version) {
            return Err(not_found("Unknown version for this apworld"));
        }
        apworld.name.clone()
    };

    let options = get_options_def(
        apworld_name,
        &parsed_version,
        &base,
        options_gen_queue,
        options_cache,
    )
    .await
    .status(Status::ServiceUnavailable)?;

    let player_name = form.get("player").map(|s| s.as_str()).unwrap_or("Player");
    let player_name = if player_name.is_empty() {
        "Player"
    } else {
        player_name
    };

    let options_query = base_query(index_manager, &base).await;
    let description = form
        .get("description")
        .filter(|s| !s.is_empty())
        .cloned()
        .unwrap_or_else(|| {
            format!("Generated on https://{host}/options/{apworld_name}{options_query}")
        });

    // Build game options in definition order
    let mut game_options: IndexMap<String, serde_json::Value> = IndexMap::new();
    for (_group_name, group_options) in options.iter() {
        for (option_name, _option_def) in group_options.iter() {
            if let Some(value) = form.get(option_name) {
                // Try to parse as JSON for complex types (lists, counters, bools, numbers)
                let parsed = serde_json::from_str::<serde_json::Value>(value)
                    .unwrap_or_else(|_| serde_json::Value::String(value.clone()));
                game_options.insert(option_name.clone(), parsed);
            }
        }
    }

    // Build the full YAML structure
    let mut root: IndexMap<String, serde_json::Value> = IndexMap::new();
    root.insert(
        "game".to_string(),
        serde_json::Value::String(game_name.clone()),
    );
    root.insert(
        "name".to_string(),
        serde_json::Value::String(player_name.to_string()),
    );
    root.insert(
        "description".to_string(),
        serde_json::Value::String(description),
    );
    root.insert(game_name.clone(), serde_json::to_value(&game_options)?);

    let yaml = serde_saphyr::to_string(&root)?;

    let value = format!("attachment; filename=\"{}.yaml\"", player_name);
    Ok(YamlDownload {
        content: yaml,
        headers: Header::new(CONTENT_DISPOSITION.as_str(), value),
    })
}

pub fn routes() -> Vec<Route> {
    rocket::routes![
        options_apworld_versions,
        options_gen_api,
        options_gen,
        edit_yaml,
        download_yaml,
    ]
}

// These need a `valkey-server` binary in the PATH, like the tests of the `wq` crate
#[cfg(test)]
mod tests {
    use super::*;
    use crate::jobs::{get_options_gen_callback, OptionDef, OptionsGenResponse};
    use crate::test_utils::{redis_pool, start_valkey, ValkeyInstance};

    const LEGACY: Version = Version::new(0, 6, 7);
    const NEWER: Version = Version::new(0, 6, 8);

    /// What one lobby process holds of the options generator
    async fn lobby_process(valkey: &ValkeyInstance) -> (OptionsGenQueue, OptionsCache) {
        let cache = OptionsCache::new(redis_pool(valkey), LEGACY);
        let queue = OptionsGenQueue::builder("options_gen")
            .with_default_partition("0.6.7")
            .with_callback(get_options_gen_callback(cache.clone()))
            .build(&valkey.url())
            .await
            .unwrap();

        (queue, cache)
    }

    fn test_options() -> OptionsDef {
        let option = OptionDef {
            default: serde_json::json!("normal"),
            description: "How hard the game is".to_string(),
            ty: "choice".to_string(),
            display_name: "Difficulty".to_string(),
            range: None,
            choices: Some(vec!["easy".to_string(), "normal".to_string()]),
            suggestions: None,
            valid_keys: None,
        };

        IndexMap::from([(
            "Game Options".to_string(),
            IndexMap::from([("difficulty".to_string(), option)]),
        )])
    }

    fn as_json(options: &OptionsDef) -> serde_json::Value {
        serde_json::to_value(options).unwrap()
    }

    #[rocket::async_test]
    async fn test_definitions_reach_a_process_that_did_not_get_the_result() {
        let valkey = start_valkey();
        let (asking_queue, asking_cache) = lobby_process(&valkey).await;
        let (resolving_queue, _resolving_cache) = lobby_process(&valkey).await;

        // The worker reports to the other process than the one serving the request
        let worker = rocket::tokio::spawn(async move {
            let job = loop {
                if let Some(job) = resolving_queue.claim_job("worker").await.unwrap() {
                    break job;
                }
            };
            let response = OptionsGenResponse {
                options: test_options(),
                error: None,
            };
            // Resolved at once, which a real worker never does: the result is then gone before
            // the process that asked has started waiting for it, and it must still be told.
            resolving_queue
                .resolve_job("worker", job.job_id, JobStatus::Success, Some(response))
                .await
                .unwrap();
        });

        let options = get_options_def(
            "world",
            &Version::new(1, 0, 0),
            &LEGACY,
            State::from(&asking_queue),
            State::from(&asking_cache),
        )
        .await
        .expect("The definitions should be available to the process that asked for them");
        worker.await.unwrap();

        assert_eq!(as_json(&options), as_json(&test_options()));
    }

    #[rocket::async_test]
    async fn test_cached_definitions_need_no_job() {
        let valkey = start_valkey();
        let (queue, cache) = lobby_process(&valkey).await;
        let version = Version::new(1, 0, 0);
        assert!(!cache.contains(&LEGACY, "world", &version).await.unwrap());

        cache
            .insert(&LEGACY, "world", &version, &test_options())
            .await
            .unwrap();

        assert!(cache.contains(&LEGACY, "world", &version).await.unwrap());
        // Nothing serves the queue here, so this only returns if the cache answers
        let options = get_options_def(
            "world",
            &version,
            &LEGACY,
            State::from(&queue),
            State::from(&cache),
        )
        .await
        .unwrap();
        assert_eq!(as_json(&options), as_json(&test_options()));
        assert!(cache
            .get(&LEGACY, "world", &Version::new(2, 0, 0))
            .await
            .unwrap()
            .is_none());
    }

    #[rocket::async_test]
    async fn test_unreadable_definitions_are_a_miss() {
        let valkey = start_valkey();
        let pool = redis_pool(&valkey);
        let cache = OptionsCache::new(pool.clone(), LEGACY);
        let version = Version::new(1, 0, 0);
        let mut redis = pool.get().await.unwrap();
        redis
            .set::<_, _, ()>(cache.key(&LEGACY, "world", &version), "not gzip")
            .await
            .unwrap();

        assert!(cache
            .get(&LEGACY, "world", &version)
            .await
            .unwrap()
            .is_none());
    }

    fn other_options() -> OptionsDef {
        let mut options = test_options();
        options.insert("Only On The Newer Base".to_string(), IndexMap::new());

        options
    }

    #[rocket::async_test]
    async fn test_definitions_of_two_bases_are_kept_apart() {
        let valkey = start_valkey();
        let (_queue, cache) = lobby_process(&valkey).await;
        let version = Version::new(1, 0, 0);

        cache
            .insert(&LEGACY, "world", &version, &test_options())
            .await
            .unwrap();
        assert!(!cache.contains(&NEWER, "world", &version).await.unwrap());

        cache
            .insert(&NEWER, "world", &version, &other_options())
            .await
            .unwrap();

        let legacy = cache.get(&LEGACY, "world", &version).await.unwrap();
        assert_eq!(as_json(&legacy.unwrap()), as_json(&test_options()));
        let newer = cache.get(&NEWER, "world", &version).await.unwrap();
        assert_eq!(as_json(&newer.unwrap()), as_json(&other_options()));
    }

    #[rocket::async_test]
    async fn test_legacy_base_keeps_the_keys_from_before_bases() {
        let valkey = start_valkey();
        let pool = redis_pool(&valkey);
        let cache = OptionsCache::new(pool.clone(), LEGACY);
        let version = Version::new(1, 0, 0);

        // What a lobby from before definitions had a base stored, and still reads
        let mut redis = pool.get().await.unwrap();
        redis
            .set::<_, _, ()>(
                "options_def:world:1.0.0",
                encode_options_def(&test_options()).unwrap(),
            )
            .await
            .unwrap();

        let found = cache.get(&LEGACY, "world", &version).await.unwrap();
        assert_eq!(as_json(&found.unwrap()), as_json(&test_options()));
        assert!(cache
            .get(&NEWER, "world", &version)
            .await
            .unwrap()
            .is_none());

        cache
            .insert(&NEWER, "world", &version, &other_options())
            .await
            .unwrap();
        let mut keys: Vec<String> = redis.keys("options_def:*").await.unwrap();
        keys.sort();
        assert_eq!(
            keys,
            [
                "options_def:base:0.6.8:world:1.0.0",
                "options_def:world:1.0.0"
            ]
        );
    }

    /// A worker for `base` that takes one job and answers it with `options`
    fn worker(
        queue: OptionsGenQueue,
        base: &'static str,
        options: OptionsDef,
    ) -> rocket::tokio::task::JoinHandle<Option<Version>> {
        rocket::tokio::spawn(async move {
            let job = loop {
                if let Some(job) = queue.claim_job_in(Some(base), "worker").await.unwrap() {
                    break job;
                }
            };
            let response = OptionsGenResponse {
                options,
                error: None,
            };
            queue
                .resolve_job("worker", job.job_id, JobStatus::Success, Some(response))
                .await
                .unwrap();

            job.params.ap_version
        })
    }

    #[rocket::async_test]
    async fn test_definitions_are_generated_by_the_base_they_are_for() {
        let valkey = start_valkey();
        let (asking_queue, cache) = lobby_process(&valkey).await;
        let (legacy_queue, _) = lobby_process(&valkey).await;
        let (newer_queue, _) = lobby_process(&valkey).await;
        let version = Version::new(1, 0, 0);

        // Both workers wait. Only the one for the base that is asked for gets the job.
        let legacy_worker = worker(legacy_queue, "0.6.7", test_options());
        let newer_worker = worker(newer_queue, "0.6.8", other_options());

        let options = get_options_def(
            "world",
            &version,
            &NEWER,
            State::from(&asking_queue),
            State::from(&cache),
        )
        .await
        .unwrap();
        assert_eq!(as_json(&options), as_json(&other_options()));
        assert_eq!(newer_worker.await.unwrap(), Some(NEWER));
        assert!(!cache.contains(&LEGACY, "world", &version).await.unwrap());

        let options = get_options_def(
            "world",
            &version,
            &LEGACY,
            State::from(&asking_queue),
            State::from(&cache),
        )
        .await
        .unwrap();
        assert_eq!(as_json(&options), as_json(&test_options()));
        assert_eq!(legacy_worker.await.unwrap(), Some(LEGACY));
    }

    #[rocket::async_test]
    async fn test_job_from_before_bases_is_stored_for_the_legacy_base() {
        let valkey = start_valkey();
        let (queue, cache) = lobby_process(&valkey).await;
        let params = OptionsGenParams {
            apworld: ("world".to_string(), Version::new(1, 0, 0)),
            otlp_context: HashMap::new(),
            ap_version: None,
        };
        queue
            .enqueue_job(&params, wq::Priority::Low, Duration::from_secs(30))
            .await
            .unwrap();

        worker(queue, "0.6.7", test_options()).await.unwrap();

        assert!(cache
            .contains(&LEGACY, "world", &Version::new(1, 0, 0))
            .await
            .unwrap());
    }
}
